// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgAuiez1a6WGjpWae3q9HRNhad6JckhY',
    appId: '1:140230492188:android:1c82728e0e7b0dbdc41fd9',
    messagingSenderId: '140230492188',
    projectId: 'luellacherine-e8612',
    databaseURL: 'https://luellacherine-e8612-default-rtdb.firebaseio.com',
    storageBucket: 'luellacherine-e8612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYxjlicHWjw9cEMZfI8jS3auIrd8w00nw',
    appId: '1:140230492188:ios:269f771fb977fc57c41fd9',
    messagingSenderId: '140230492188',
    projectId: 'luellacherine-e8612',
    databaseURL: 'https://luellacherine-e8612-default-rtdb.firebaseio.com',
    storageBucket: 'luellacherine-e8612.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9jUpFC3hojLDor9MP7lj3l3ZuaCKxs_A',
    appId: '1:140230492188:web:f68f65389f3d2a40c41fd9',
    messagingSenderId: '140230492188',
    projectId: 'luellacherine-e8612',
    authDomain: 'luellacherine-e8612.firebaseapp.com',
    databaseURL: 'https://luellacherine-e8612-default-rtdb.firebaseio.com',
    storageBucket: 'luellacherine-e8612.firebasestorage.app',
    measurementId: 'G-3GHBEHT172',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYxjlicHWjw9cEMZfI8jS3auIrd8w00nw',
    appId: '1:140230492188:ios:269f771fb977fc57c41fd9',
    messagingSenderId: '140230492188',
    projectId: 'luellacherine-e8612',
    databaseURL: 'https://luellacherine-e8612-default-rtdb.firebaseio.com',
    storageBucket: 'luellacherine-e8612.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9jUpFC3hojLDor9MP7lj3l3ZuaCKxs_A',
    appId: '1:140230492188:web:6c955a20b18e3e43c41fd9',
    messagingSenderId: '140230492188',
    projectId: 'luellacherine-e8612',
    authDomain: 'luellacherine-e8612.firebaseapp.com',
    databaseURL: 'https://luellacherine-e8612-default-rtdb.firebaseio.com',
    storageBucket: 'luellacherine-e8612.firebasestorage.app',
    measurementId: 'G-QP3G20QGP9',
  );

}